### ISSUE TITLE
Version 0.33 fails is usage by https://github.com/doy/parse-keyword

### ISSUE THREAD

**Issue by pwr22** [avar/dist-zilla-plugin-makemaker-awesome#6]
When trying `dzil build` I'm getting the following output

	peter@dev ~/parse-keyword (pwr22-PRC)> dzil build
	!!! [EOLTests] is deprecated and may be removed in a future release; replace it with [Test::EOL] (note the different default filename)
	 at /home/peter/.perlbrew/libs/5.20.1@general/lib/perl5/x86_64-linux/Class/MOP/Method/Wrapped.pm line 42.
	[DZ] beginning to build Parse-Keyword
	[@DOY/Git::NextVersion] Bumping version from 0.08 to 0.09
	[DZ] guessing dist's main_module is lib/Parse/Keyword.pm
	Can't call method "content" on an undefined value at /home/peter/.perlbrew/libs/5.20.1@general/lib/perl5/Dist/Zilla/Plugin/MakeMaker/Awesome.pm line 392.

**Comment by karenetheridge** [comment]
The problem is here: https://metacpan.org/source/DOY/Parse-Keyword-0.08/dist.ini#L33

`Makefile.PL` is being added by MakeMaker::Awesome, and then the dist.ini is pruning it.  `[PruneFiles]` should be replaced by a modifier on the bundle to either remove `[GatherDir]` and then re-add it with the extra parameter `exclude_filename = Makefile.PL`, or modify the `[GatherDir]` in the bundle to set that config. (I use Dist::Zilla::Role::PluginBundle::PluginRemover and Dist::Zilla::Role::PluginBundle::Config::Slicer in my bundle to do those things, respectively.)  So, this is a bug for Dist::Zilla::PluginBundle::DOY!

(You can also downgrade MakeMaker::Awesome to version 0.22 to go back to before the filegathering logic was changed.)

**Comment by pwr22** [comment]
Thanks  for point me in the right direction :)
